version: '3.3'

services:
    postgres:
      container_name: hardwareshopdb
      image: postgres:14.3
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - ./postgres:/var/lib/postgresql/data